Description: Stack for Dragonchain Seed (seed.raiinmaker.com)

Resources:
  
  # BUCKETS
  ProductionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rm-raiinmaker-admin-ui-prod
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  ProductionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProductionBucket
      PolicyDocument:
        Id: rm-raiinmaker-admin-ui-prod-bucket-policy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ProductionBucket
                - /*

# DISTRIBUTION
  ProductionDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: rm-raiinmaker-admin-ui-prod.s3.amazonaws.com
            Id: S3-raiinmaker-admin-ui-prod
            S3OriginConfig: {}
        Enabled: 'true'
        Comment: Raiinmaker Admin UI Production
        DefaultRootObject: index.html
        CustomErrorResponses:
            - ErrorCode: 404
              ErrorCachingMinTTL: 0
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 403
              ErrorCachingMinTTL: 0
              ResponseCode: 200
              ResponsePagePath: /index.html
        Aliases:
        - seed.raiinmaker.com
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          DefaultTTL: 31536000
          MaxTTL: 315360000
          MinTTL: 0
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          TargetOriginId: S3-raiinmaker-admin-ui-prod
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: 'arn:aws:acm:us-east-1:527252880472:certificate/4e7ce8fc-1721-4399-afdb-9b66d1b77f73'
          SslSupportMethod: 'sni-only'   
    DependsOn: ProductionBucket

# DNS RECORDS
  ProductionDNSRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: raiinmaker.com.
      RecordSets:
      - Name: seed.raiinmaker.com.
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt ProductionDistribution.DomainName
      - Name: seed.raiinmaker.com.
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt ProductionDistribution.DomainName
    DependsOn: ProductionDistribution
